### PR TITLE
Webpack Build progress

### PR DESCRIPTION
**Pull request by p-rk**
Elint fixes
Now showing the webpack build progress in cli during development mode

### CODE REVIEW

**Comment by bertho-zero** [comment]
https://www.npmjs.com/package/webpackbar

I think you can add this plugin for both dev and prod configs, with the following parameters:

```js
new ProgressBar({ minimal: false })
```

I use it at work and it's pleasant.

**Comment by p-rk** [comment]
But @bertho-zero this is an external dev dependency right which adds load again on top of dev server. But in my PR I'm directly using the ProgressPlugin() which comes with webpack internals no external dependency or fancy status needed in my suggestion, Dev server take a lot of time to compile once your project grows as I'm faced in my application which is in production right now.

**Comment by bertho-zero** [comment]
It would not be good in `webpack/dev.config.js` and `webpack/prod.config.js`, rather than just `webpack/webpack-dev-server.js` ?

**Comment by p-rk** [comment]
@bertho-zero I've updated it now. Extended to prod config and dev config.
Removed from dev-server

**Pull request merged**
